/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface BalanceEvent { 'timestamp' : bigint, 'amount' : bigint }
export interface TollPlaza {
  'id' : string,
  'latitude' : number,
  'name' : string,
  'highway' : string,
  'tollRates' : TollRates,
  'longitude' : number,
}
export interface TollRates {
  'lcv' : bigint,
  'mav' : bigint,
  'oversized' : bigint,
  'multiAxle' : bigint,
  'busTruck' : bigint,
  'carJeepVan' : bigint,
}
export interface Transaction {
  'plazaName' : string,
  'vehicleType' : string,
  'amountDeducted' : bigint,
  'plazaId' : string,
  'timestamp' : bigint,
  'balanceAfter' : bigint,
  'balanceBefore' : bigint,
}
export interface _SERVICE {
  'addTollPlaza' : ActorMethod<[TollPlaza], undefined>,
  'clearTransactions' : ActorMethod<[], undefined>,
  'deductToll' : ActorMethod<[string, string], boolean>,
  'getAllTollPlazas' : ActorMethod<[], Array<TollPlaza>>,
  'getBalance' : ActorMethod<[], bigint>,
  'getBalanceHistory' : ActorMethod<[], Array<BalanceEvent>>,
  'getTollPlaza' : ActorMethod<[string], TollPlaza>,
  'getTransactions' : ActorMethod<[], Array<Transaction>>,
  'getVehicleType' : ActorMethod<[], string>,
  'recharge' : ActorMethod<[bigint], bigint>,
  'setBalance' : ActorMethod<[bigint], undefined>,
  'setVehicleType' : ActorMethod<[string], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];