/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const TollRates = IDL.Record({
  'lcv' : IDL.Nat,
  'mav' : IDL.Nat,
  'oversized' : IDL.Nat,
  'multiAxle' : IDL.Nat,
  'busTruck' : IDL.Nat,
  'carJeepVan' : IDL.Nat,
});
export const TollPlaza = IDL.Record({
  'id' : IDL.Text,
  'latitude' : IDL.Float64,
  'name' : IDL.Text,
  'highway' : IDL.Text,
  'tollRates' : TollRates,
  'longitude' : IDL.Float64,
});
export const BalanceEvent = IDL.Record({
  'timestamp' : IDL.Int,
  'amount' : IDL.Nat,
});
export const Transaction = IDL.Record({
  'plazaName' : IDL.Text,
  'vehicleType' : IDL.Text,
  'amountDeducted' : IDL.Nat,
  'plazaId' : IDL.Text,
  'timestamp' : IDL.Int,
  'balanceAfter' : IDL.Nat,
  'balanceBefore' : IDL.Nat,
});

export const idlService = IDL.Service({
  'addTollPlaza' : IDL.Func([TollPlaza], [], []),
  'clearTransactions' : IDL.Func([], [], []),
  'deductToll' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
  'getAllTollPlazas' : IDL.Func([], [IDL.Vec(TollPlaza)], ['query']),
  'getBalance' : IDL.Func([], [IDL.Nat], ['query']),
  'getBalanceHistory' : IDL.Func([], [IDL.Vec(BalanceEvent)], ['query']),
  'getTollPlaza' : IDL.Func([IDL.Text], [TollPlaza], ['query']),
  'getTransactions' : IDL.Func([], [IDL.Vec(Transaction)], ['query']),
  'getVehicleType' : IDL.Func([], [IDL.Text], ['query']),
  'recharge' : IDL.Func([IDL.Nat], [IDL.Nat], []),
  'setBalance' : IDL.Func([IDL.Nat], [], []),
  'setVehicleType' : IDL.Func([IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const TollRates = IDL.Record({
    'lcv' : IDL.Nat,
    'mav' : IDL.Nat,
    'oversized' : IDL.Nat,
    'multiAxle' : IDL.Nat,
    'busTruck' : IDL.Nat,
    'carJeepVan' : IDL.Nat,
  });
  const TollPlaza = IDL.Record({
    'id' : IDL.Text,
    'latitude' : IDL.Float64,
    'name' : IDL.Text,
    'highway' : IDL.Text,
    'tollRates' : TollRates,
    'longitude' : IDL.Float64,
  });
  const BalanceEvent = IDL.Record({
    'timestamp' : IDL.Int,
    'amount' : IDL.Nat,
  });
  const Transaction = IDL.Record({
    'plazaName' : IDL.Text,
    'vehicleType' : IDL.Text,
    'amountDeducted' : IDL.Nat,
    'plazaId' : IDL.Text,
    'timestamp' : IDL.Int,
    'balanceAfter' : IDL.Nat,
    'balanceBefore' : IDL.Nat,
  });
  
  return IDL.Service({
    'addTollPlaza' : IDL.Func([TollPlaza], [], []),
    'clearTransactions' : IDL.Func([], [], []),
    'deductToll' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
    'getAllTollPlazas' : IDL.Func([], [IDL.Vec(TollPlaza)], ['query']),
    'getBalance' : IDL.Func([], [IDL.Nat], ['query']),
    'getBalanceHistory' : IDL.Func([], [IDL.Vec(BalanceEvent)], ['query']),
    'getTollPlaza' : IDL.Func([IDL.Text], [TollPlaza], ['query']),
    'getTransactions' : IDL.Func([], [IDL.Vec(Transaction)], ['query']),
    'getVehicleType' : IDL.Func([], [IDL.Text], ['query']),
    'recharge' : IDL.Func([IDL.Nat], [IDL.Nat], []),
    'setBalance' : IDL.Func([IDL.Nat], [], []),
    'setVehicleType' : IDL.Func([IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };