/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface TollRates {
    lcv: bigint;
    mav: bigint;
    oversized: bigint;
    multiAxle: bigint;
    busTruck: bigint;
    carJeepVan: bigint;
}
export interface BalanceEvent {
    timestamp: bigint;
    amount: bigint;
}
export interface TollPlaza {
    id: string;
    latitude: number;
    name: string;
    highway: string;
    tollRates: TollRates;
    longitude: number;
}
export interface Transaction {
    plazaName: string;
    vehicleType: string;
    amountDeducted: bigint;
    plazaId: string;
    timestamp: bigint;
    balanceAfter: bigint;
    balanceBefore: bigint;
}
export interface backendInterface {
    addTollPlaza(plaza: TollPlaza): Promise<void>;
    clearTransactions(): Promise<void>;
    deductToll(plazaId: string, vehicleType: string): Promise<boolean>;
    getAllTollPlazas(): Promise<Array<TollPlaza>>;
    getBalance(): Promise<bigint>;
    getBalanceHistory(): Promise<Array<BalanceEvent>>;
    getTollPlaza(id: string): Promise<TollPlaza>;
    getTransactions(): Promise<Array<Transaction>>;
    getVehicleType(): Promise<string>;
    recharge(amount: bigint): Promise<bigint>;
    setBalance(newBalance: bigint): Promise<void>;
    setVehicleType(newVehicleType: string): Promise<void>;
}
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async addTollPlaza(arg0: TollPlaza): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addTollPlaza(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addTollPlaza(arg0);
            return result;
        }
    }
    async clearTransactions(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.clearTransactions();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.clearTransactions();
            return result;
        }
    }
    async deductToll(arg0: string, arg1: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deductToll(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deductToll(arg0, arg1);
            return result;
        }
    }
    async getAllTollPlazas(): Promise<Array<TollPlaza>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllTollPlazas();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllTollPlazas();
            return result;
        }
    }
    async getBalance(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getBalance();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBalance();
            return result;
        }
    }
    async getBalanceHistory(): Promise<Array<BalanceEvent>> {
        if (this.processError) {
            try {
                const result = await this.actor.getBalanceHistory();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBalanceHistory();
            return result;
        }
    }
    async getTollPlaza(arg0: string): Promise<TollPlaza> {
        if (this.processError) {
            try {
                const result = await this.actor.getTollPlaza(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTollPlaza(arg0);
            return result;
        }
    }
    async getTransactions(): Promise<Array<Transaction>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTransactions();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTransactions();
            return result;
        }
    }
    async getVehicleType(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.getVehicleType();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getVehicleType();
            return result;
        }
    }
    async recharge(arg0: bigint): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.recharge(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.recharge(arg0);
            return result;
        }
    }
    async setBalance(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setBalance(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setBalance(arg0);
            return result;
        }
    }
    async setVehicleType(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setVehicleType(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setVehicleType(arg0);
            return result;
        }
    }
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
